org: rickhenry
app: rhd-airtable
service: rhd-airtable

frameworkVersion: '2'

plugins:
  - serverless-plugin-typescript
  - serverless-domain-manager

custom:
  customDomain:
    domainName: rhdapi.click
    basePath: ${self:provider.stage}
    stage: ${self:provider.stage}
    createRoute53Record: true
    autoDomain: true
    endpointType: regional
    apiType: http

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

  stage: ${opt:stage, 'dev'}
  region: us-east-1

  environment:
    AIRTABLE_API_KEY: ${param:AIRTABLE_API_KEY}
    AIRTABLE_BASE_ID: ${param:AIRTABLE_BASE_ID}

functions:
  full-projects:
    handler: functions/full-projects.main
    events:
      - httpApi:
          path: /full-projects
          method: get

  index-projects:
    handler: functions/index-projects.main
    events:
      - httpApi:
          path: /index-projects
          method: get
