org: rickhenry
app: rhd-airtable
service: rhd-airtable

frameworkVersion: '2'

plugins:
  - serverless-plugin-typescript


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

  stage: dev
  region: us-east-1

  environment:
    AIRTABLE_API_KEY: ${param:AIRTABLE_API_KEY}
    AIRTABLE_BASE_ID: ${param:AIRTABLE_BASE_ID}

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
